site_name: Studiversity
repo_url: https://github.com/denchic45/Studiversity
repo_name: denchic45/Studiversity
theme:
  language: ru
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand

nav:
    - Начало: 'index.md'
    - Руководство пользователя:
        - Обзор: 'user-guide/overview.md'
        - Для преподавателей: 'user-guide/teacher.md'
        - Для студентов: 'user-guide/student.md'
        - Для модераторов: 'user-guide/moderator.md'
    - Руководство разработчика:
        - Развертывание сервера: 'dev-guide/deploy.md'
        - API документация: 'dev-guide/api.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
   - swagger-ui-tag
   - glightbox