package com.denchic45.studiversity.feature.role

object RoleErrors {
    const val PERMISSION_DENIED = "PERMISSION_DENIED"
    const val NOT_AVAILABLE_ROLE_IN_SCOPE = "NOT_AVAILABLE_ROLE_IN_SCOPE"
    const val PERMISSION_DENIED_TO_ASSIGN_ROLE = "NOT_PERMISSION_ASSIGN_ROLE"
    const val NOT_FOUND_ROLE = "NOT_FOUND_ROLE"
    const val NO_ROLE_ASSIGNMENT = "NO_ROLE_ASSIGNMENT"
    const val ROLES_DUPLICATION = "ROLES_DUPLICATION"
}