package com.denchic45.kts.ui.theme

import androidx.compose.ui.graphics.Color

private const val DividerAlpha = 0.12f

val md_theme_light_primary = Color(0xFF0159C6)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD9E2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001A43)
val md_theme_light_secondary = Color(0xFF295EA7)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD6E3FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001B3E)
val md_theme_light_tertiary = Color(0xFF7D5800)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDEA9)
val md_theme_light_onTertiaryContainer = Color(0xFF271900)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44464F)
val md_theme_light_outline = Color(0xFF1B1B1F).copy(alpha = 0.26f)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFAFC6FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF0159C6)
val md_theme_light_surfaceTintColor = Color(0xFF0159C6)

val md_theme_dark_primary = Color(0xFFAFC6FF)
val md_theme_dark_onPrimary = Color(0xFF002D6C)
val md_theme_dark_primaryContainer = Color(0xFF004398)
val md_theme_dark_onPrimaryContainer = Color(0xFFD9E2FF)
val md_theme_dark_secondary = Color(0xFFA9C7FF)
val md_theme_dark_onSecondary = Color(0xFF003063)
val md_theme_dark_secondaryContainer = Color(0xFF00468C)
val md_theme_dark_onSecondaryContainer = Color(0xFFD6E3FF)
val md_theme_dark_tertiary = Color(0xFFF9BC47)
val md_theme_dark_onTertiary = Color(0xFF422C00)
val md_theme_dark_tertiaryContainer = Color(0xFF5E4100)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDEA9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE3E2E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE3E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF44464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C6D0)
val md_theme_dark_outline = Color(0xFF8F9099)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE3E2E6)
val md_theme_dark_inversePrimary = Color(0xFF0159C6)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFAFC6FF)
val md_theme_dark_surfaceTintColor = Color(0xFFAFC6FF)


val seed = Color(0xFF3473E1)
val Succes = Color(0xFF34A853)
val light_Succes = Color(0xFF006E2C)
val light_onSucces = Color(0xFFFFFFFF)
val light_SuccesContainer = Color(0xFF89FA9B)
val light_onSuccesContainer = Color(0xFF002108)
val dark_Succes = Color(0xFF6DDD81)
val dark_onSucces = Color(0xFF003914)
val dark_SuccesContainer = Color(0xFF005320)
val dark_onSuccesContainer = Color(0xFF89FA9B)