package com.denchic45.stuiversity.api.auth

object AuthErrors {
    const val REFRESH_TOKEN_REQUIRED = "REFRESH_TOKEN_REQUIRED"
    const val USER_ALREADY_REGISTERED = "USER_ALREADY_REGISTERED"
    const val PASSWORD_MUST_CONTAIN_AT_LEAST_6_CHARACTERS = "PASSWORD_MUST_CONTAIN_AT_LEAST_6_CHARACTERS"
    const val PASSWORD_MUST_CONTAIN_UPPER_AND_LOWER_CASE_CHARACTERS =
        "PASSWORD_MUST_CONTAIN_UPPER_AND_LOWER_CASE_CHARACTERS"
    const val PASSWORD_MUST_CONTAIN_DIGITS = "PASSWORD_MUST_CONTAIN_DIGITS"
    const val INVALID_GRANT = "INVALID_GRANT"
    const val INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    const val INVALID_EMAIL = "INVALID_EMAIL"
    const val INVALID_PASSWORD = "INVALID_PASSWORD"
    const val INVALID_OLD_PASSWORD = "INVALID_OLD_PASSWORD"
    const val INVALID_MAGIC_LINK = "INVALID_MAGIC_LINK"
}

enum class AuthErrs:ErrorReason { REFRESH_TOKEN_REQUIRED, USER_ALREADY_REGISTERED}

interface ErrorReason {
//    val reason:String
}